spring.datasource.url=jdbc:postgresql://localhost:5432/municipal_transport
spring.datasource.username=postgres
spring.datasource.password=${DB_PASSWORD:0000}

spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.show-sql=false

# Jackson : sérialise LocalDate en "2024-12-31" (ISO) au lieu de [2024,12,31]
spring.jackson.serialization.write-dates-as-timestamps=false
spring.jackson.deserialization.fail-on-unknown-properties=false

# Exécute data.sql APRÈS que Hibernate ait créé/mis à jour le schéma
spring.jpa.defer-datasource-initialization=true
spring.sql.init.mode=always
spring.sql.init.continue-on-error=true

# CORS
app.cors.allowed-origins=http://localhost:4200

<<<<<<< HEAD
# JWT
jwt.secret=municipal-transport-jwt-secret-key-2026-smartbus-secure-256bits
jwt.expiration=86400000

=======
>>>>>>> f141314d577dc66fb48869aa744bb9618de13ced
# Chatbot Groq (LLM + RAG)
groq.api.key=${GROQ_API_KEY:}
groq.api.url=https://api.groq.com/openai/v1/chat/completions
groq.model=llama-3.1-8b-instant